name: release

on:
  push:
    tags:
      - "v*.*.*"

env:
  RELEASE_NAME: no-creeper-anxiety
  PUBLIC_URL: /no-creeper-anxiety/

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version-tag.outputs.VERSION }}
    steps:
      - name: Get tagged version
        id: version-tag
        run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"

  build-jar:
    needs: setup
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Rename
        run: |
          mv ./build/libs/nocreeperanxiety-${{ needs.setup.outputs.version }}.jar ./${{ env.RELEASE_NAME }}-${{ needs.setup.outputs.version }}.jar
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: ./${{ env.RELEASE_NAME }}-${{ needs.setup.outputs.version }}.jar
